# Generated by Django 5.2.7 on 2025-11-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_channel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
