# Generated by Django 5.2.7 on 2025-11-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
